### ISSUE TITLE
v0.4 roadmap

### ISSUE THREAD

**Issue by imcotton** [imcotton/match#1]
WIP
- [ ] Replacing Angular with React
- [ ] Replacing Underscore with Lo-Dash
- [ ] Dropping IE8 support

**Comment by imcotton** [comment]
no longer valid in favor of v1.0.0
